import type { AIProvider } from '../types/ai.types';
import { TaskType } from '../types/ai.types';

export const PROVIDER_PRIORITY_ORDER = [
  'puter',
  'opencode',
  'openrouter',
  'groq',
  'gemini',
  'mistral',
  'sambanova',
  'zai',
  'ollama',
] as const satisfies readonly AIProvider[];

export const FALLBACK_CHAIN = [
  'puter',
  'opencode',
  'openrouter',
  'groq',
  'gemini',
  'mistral',
  'sambanova',
  'zai',
  'ollama',
] as const satisfies readonly AIProvider[];

export const TASK_PROVIDER_MAP = {
  [TaskType.CODE_GENERATION]: [
    'opencode',
    'openrouter',
    'groq',
    'gemini',
    'mistral',
    'sambanova',
    'zai',
    'ollama',
    'puter',
  ],
  [TaskType.CODE_REVIEW]: [
    'openrouter',
    'gemini',
    'mistral',
    'opencode',
    'groq',
    'zai',
    'sambanova',
    'ollama',
    'puter',
  ],
  [TaskType.DEBUGGING]: [
    'opencode',
    'openrouter',
    'gemini',
    'groq',
    'mistral',
    'zai',
    'sambanova',
    'ollama',
    'puter',
  ],
  [TaskType.DOCUMENTATION]: [
    'mistral',
    'gemini',
    'openrouter',
    'groq',
    'opencode',
    'zai',
    'sambanova',
    'ollama',
    'puter',
  ],
  [TaskType.EXPLANATION]: [
    'gemini',
    'openrouter',
    'mistral',
    'groq',
    'zai',
    'opencode',
    'sambanova',
    'ollama',
    'puter',
  ],
  [TaskType.REFACTORING]: [
    'opencode',
    'openrouter',
    'mistral',
    'gemini',
    'groq',
    'zai',
    'sambanova',
    'ollama',
    'puter',
  ],
  [TaskType.TEST_GENERATION]: [
    'opencode',
    'groq',
    'openrouter',
    'gemini',
    'mistral',
    'sambanova',
    'zai',
    'ollama',
    'puter',
  ],
} as const satisfies Record<TaskType, readonly AIProvider[]>;
